[target.'x86_64-unknown-linux-gnu']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "target-cpu=native"]
[build]
target-dir = ".cache/cargo/target"
[net]
git-fetch-with-cli = true
