#!/bin/bash
# Based on http://openweathermap.org/current

sleep 3 # wait for wifi maybe

# Check on http://openweathermap.org/find
CITY_ID="5392171"

URGENT_LOWER=5
URGENT_HIGHER=25

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="°C"

WEATHER_URL="https://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=cdff7006344be717c33df246a5c01cc9&units=metric"

WEATHER_INFO=$(curl "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | jq -r '.weather[].main')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | jq -r '.main.temp | round')

#if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
#  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo ""
#elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
#  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo ""
#elif [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
#  echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo ""
#elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
#  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo ""
#elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
#  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo ""
#elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
#  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#  echo ""
#else
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${WEATHER_TEMP}${SYMBOL_CELSIUS}"
#fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
