#!/bin/sh
case $button in
	1)
		cd $DIR
		i3-sensible-terminal -d $DIR
		;;
esac
cd $DIR
if test "$(git status --porcelain | wc -l)" -gt 0; then
	if test -z $ALWAYS_SHORT; then
		echo DIRTY
	else
		echo D
	fi
	echo D
	echo '#ff3333'
else
	if test -z $ALWAYS_SHORT; then
		echo CLEAN
	else
		echo C
	fi
	echo C
fi
